# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='date')),
                ('title', models.CharField(max_length=1000)),
                ('subtitle', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=500)),
                ('body', models.TextField()),
            ],
        ),
    ]
